// apps/mobile/src/components/modals/ContactMergeModal.tsx
import { useState, useEffect } from 'react';
import { View, Text, Modal, Pressable, ScrollView } from 'react-native';
import { Users, ArrowRight, Check, X } from 'lucide-react-native';
import { useI18nStore } from '@/lib/i18n';

interface ClientData {
  name: string;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
}

interface Difference {
  field: string;
  old: string | null;
  new: string | null;
}

type MergeDecision = 'keep' | 'use_new' | 'update';

interface ContactMergeModalProps {
  visible: boolean;
  onClose: () => void;
  existingData: ClientData;
  newData: ClientData;
  differences: Difference[];
  onDecision: (decision: MergeDecision) => void;
}

const FIELD_LABELS: Record<string, string> = {
  email: 'Email',
  phone: 'Phone',
  address: 'Address',
};

function formatFieldLabel(field: string): string {
  return FIELD_LABELS[field] || field;
}

interface OptionConfig {
  decision: MergeDecision;
  iconBg: string;
  iconColor: string;
  titleKey: string;
  description: string;
  isHighlighted: boolean;
  icon: React.ReactNode;
}

export function ContactMergeModal({
  visible,
  onClose,
  existingData,
  newData,
  differences,
  onDecision,
}: ContactMergeModalProps) {
  const { t } = useI18nStore();
  const [isProcessing, setIsProcessing] = useState(false);
  const [selectedOption, setSelectedOption] = useState<MergeDecision | null>(null);

  useEffect(() => {
    if (visible) {
      setIsProcessing(false);
      setSelectedOption(null);
    }
  }, [visible]);

  function handleClose() {
    if (isProcessing) return;
    onClose();
  }

  function handleDecision(decision: MergeDecision) {
    if (isProcessing) return;
    setIsProcessing(true);
    setSelectedOption(decision);
    onDecision(decision);
  }

  const options: OptionConfig[] = [
    {
      decision: 'keep',
      iconBg: 'bg-gray-100',
      iconColor: '#475569',
      titleKey: 'merge.keepExisting',
      description: 'Use existing client data, ignore new',
      isHighlighted: false,
      icon: <Check size={18} color="#475569" />,
    },
    {
      decision: 'use_new',
      iconBg: 'bg-amber-50',
      iconColor: '#F59E0B',
      titleKey: 'merge.useNew',
      description: 'Use new data for this document only',
      isHighlighted: false,
      icon: <ArrowRight size={18} color="#F59E0B" />,
    },
    {
      decision: 'update',
      iconBg: 'bg-blue-50',
      iconColor: '#0066FF',
      titleKey: 'merge.updateBoth',
      description: 'Update client record with new data',
      isHighlighted: true,
      icon: <Users size={18} color="#0066FF" />,
    },
  ];

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={handleClose}
      statusBarTranslucent
    >
      {/* Backdrop */}
      <Pressable
        className="flex-1 justify-end"
        style={{ backgroundColor: 'rgba(0,0,0,0.3)' }}
        onPress={handleClose}
      >
        {/* Modal content */}
        <Pressable className="w-full" onPress={() => {}}>
          <View className="rounded-t-3xl px-6 pt-3 pb-10 max-h-[85%]" style={{ backgroundColor: 'rgba(255,255,255,0.95)' }}>
            {/* Drag handle */}
            <View className="w-9 h-1.5 bg-gray-300 rounded-full self-center mb-5" />

            {/* Close button */}
            <Pressable
              className="absolute top-3 right-3 w-9 h-9 rounded-full bg-gray-100 items-center justify-center z-10"
              onPress={handleClose}
              hitSlop={8}
            >
              <X size={18} color="#64748B" />
            </Pressable>

            <ScrollView showsVerticalScrollIndicator={false}>
              {/* Icon + title */}
              <View className="items-center mb-5">
                <View className="w-[72px] h-[72px] rounded-full bg-amber-50 items-center justify-center mb-4">
                  <Users size={28} color="#F59E0B" />
                </View>
                <Text className="text-[22px] font-bold text-gray-900 text-center mb-2">
                  {t('merge.title')}
                </Text>
                <Text className="text-sm text-gray-500 text-center leading-5">
                  {t('merge.description').replace('{name}', existingData.name)}
                </Text>
              </View>

              {/* Differences */}
              <View className="bg-gray-50 rounded-xl p-3 mb-5">
                {differences.map((diff, index) => (
                  <View
                    key={diff.field}
                    className={`bg-white rounded-lg p-3 ${
                      index < differences.length - 1 ? 'mb-2' : ''
                    }`}
                  >
                    <Text className="text-[11px] font-semibold uppercase tracking-wider text-gray-400 mb-1">
                      {formatFieldLabel(diff.field)}
                    </Text>
                    <View className="flex-row items-center gap-2">
                      <Text className="flex-1 text-[13px] text-gray-500 line-through" numberOfLines={2}>
                        {diff.old || '\u2014'}
                      </Text>
                      <ArrowRight size={14} color="#CBD5E1" />
                      <Text className="flex-1 text-[13px] font-semibold text-gray-900 text-right" numberOfLines={2}>
                        {diff.new || '\u2014'}
                      </Text>
                    </View>
                  </View>
                ))}
              </View>

              {/* Options */}
              <View className="gap-2.5 mb-4">
                {options.map((option) => {
                  const isSelected = selectedOption === option.decision;
                  const borderClass = option.isHighlighted
                    ? 'border-2 border-blue-200'
                    : 'border-2 border-gray-100';

                  return (
                    <Pressable
                      key={option.decision}
                      className={`flex-row items-center gap-3 p-3.5 rounded-xl ${borderClass} ${
                        isSelected ? 'opacity-50' : ''
                      }`}
                      onPress={() => handleDecision(option.decision)}
                      disabled={isProcessing}
                    >
                      <View
                        className={`w-10 h-10 rounded-[10px] items-center justify-center ${option.iconBg}`}
                      >
                        {option.icon}
                      </View>
                      <View className="flex-1">
                        <Text className="text-[15px] font-semibold text-gray-900">
                          {t(option.titleKey)}
                        </Text>
                        <Text className="text-xs text-gray-500 mt-0.5">
                          {option.description}
                        </Text>
                      </View>
                    </Pressable>
                  );
                })}
              </View>

              {/* Cancel */}
              <Pressable
                className="items-center py-3"
                onPress={handleClose}
                disabled={isProcessing}
              >
                <Text className="text-sm font-medium text-gray-500">
                  {t('common.cancel')}
                </Text>
              </Pressable>
            </ScrollView>
          </View>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

// src/lib/components/modals/ContactMergeModal.svelte
<script lang="ts">
	import { fly, fade } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import { t } from '$lib/i18n';
	import Users from 'lucide-svelte/icons/users';
	import ArrowRight from 'lucide-svelte/icons/arrow-right';
	import Check from 'lucide-svelte/icons/check';
	import X from 'lucide-svelte/icons/x';

	interface ClientData {
		name: string;
		email?: string | null;
		phone?: string | null;
		address?: string | null;
	}

	interface Difference {
		field: string;
		old: string | null;
		new: string | null;
	}

	interface ConflictData {
		existingClient: ClientData;
		newData: ClientData;
		differences: Difference[];
	}

	interface Props {
		open: boolean;
		conflictData: ConflictData | null;
		onClose: () => void;
		onDecision: (decision: 'keep' | 'use_new' | 'update') => void;
	}

	let { open = $bindable(), conflictData, onClose, onDecision }: Props = $props();

	let isProcessing = $state(false);

	function handleClose() {
		if (isProcessing) return;
		open = false;
		onClose();
	}

	function handleDecision(decision: 'keep' | 'use_new' | 'update') {
		if (isProcessing) return;
		isProcessing = true;
		onDecision(decision);
		// The parent component should close this modal after processing
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === 'Escape' && !isProcessing) {
			handleClose();
		}
	}

	function formatFieldLabel(field: string): string {
		const labels: Record<string, string> = {
			email: 'Email',
			phone: 'Phone',
			address: 'Address'
		};
		return labels[field] || field;
	}

	// Reset state when modal opens
	$effect(() => {
		if (open) {
			isProcessing = false;
		}
	});
</script>

<svelte:window onkeydown={handleKeyDown} />

{#if open && conflictData}
	<!-- Backdrop -->
	<button
		class="modal-backdrop"
		onclick={handleClose}
		aria-label={$t('aria.closeModal')}
		transition:fade={{ duration: 200 }}
	></button>

	<!-- Modal -->
	<div
		class="modal-container"
		role="dialog"
		aria-modal="true"
		aria-labelledby="merge-modal-title"
		transition:fly={{ y: 50, duration: 300, easing: cubicOut }}
	>
		<div class="modal-content">
			<!-- Close button -->
			<button class="close-btn" onclick={handleClose} aria-label={$t('common.close')}>
				<X size={20} />
			</button>

			<div class="modal-step">
				<div class="icon-wrapper">
					<Users size={28} />
				</div>

				<h2 id="merge-modal-title" class="modal-title">
					{$t('merge.title')}
				</h2>

				<p class="modal-description">
					{$t('merge.description').replace('{name}', conflictData.existingClient.name)}
				</p>

				<!-- Differences display -->
				<div class="differences-list">
					{#each conflictData.differences as diff}
						<div class="difference-item">
							<span class="diff-label">{formatFieldLabel(diff.field)}</span>
							<div class="diff-values">
								<span class="diff-old">
									{diff.old || '—'}
								</span>
								<ArrowRight size={14} class="diff-arrow" />
								<span class="diff-new">
									{diff.new || '—'}
								</span>
							</div>
						</div>
					{/each}
				</div>

				<!-- Action buttons -->
				<div class="action-options">
					<button class="option-btn" onclick={() => handleDecision('keep')} disabled={isProcessing}>
						<div class="option-icon keep">
							<Check size={18} />
						</div>
						<div class="option-text">
							<span class="option-title">{$t('merge.keepExisting')}</span>
							<span class="option-desc">Use existing client data, ignore new</span>
						</div>
					</button>

					<button
						class="option-btn"
						onclick={() => handleDecision('use_new')}
						disabled={isProcessing}
					>
						<div class="option-icon use-new">
							<ArrowRight size={18} />
						</div>
						<div class="option-text">
							<span class="option-title">{$t('merge.useNew')}</span>
							<span class="option-desc">Use new data for this document only</span>
						</div>
					</button>

					<button
						class="option-btn highlight"
						onclick={() => handleDecision('update')}
						disabled={isProcessing}
					>
						<div class="option-icon update">
							<Users size={18} />
						</div>
						<div class="option-text">
							<span class="option-title">{$t('merge.updateBoth')}</span>
							<span class="option-desc">Update client record with new data</span>
						</div>
					</button>
				</div>

				<button class="cancel-btn" onclick={handleClose} disabled={isProcessing}>
					{$t('common.cancel')}
				</button>
			</div>
		</div>
	</div>
{/if}

<style>
	.modal-backdrop {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.5);
		backdrop-filter: blur(4px);
		-webkit-backdrop-filter: blur(4px);
		z-index: 1000;
		border: none;
		cursor: default;
	}

	.modal-container {
		position: fixed;
		inset: 0;
		display: flex;
		align-items: flex-end;
		justify-content: center;
		z-index: 1001;
		padding: 0;
		overflow-y: auto;
	}

	.modal-content {
		position: relative;
		background: rgba(255, 255, 255, 0.98);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
		border-radius: var(--radius-lg) var(--radius-lg) 0 0;
		padding: 32px 24px calc(24px + var(--safe-area-bottom, 0px));
		max-width: 400px;
		width: 100%;
		max-height: calc(100vh - 40px);
		overflow-y: auto;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
	}

	.modal-content::before {
		content: '';
		position: absolute;
		top: 8px;
		left: 50%;
		transform: translateX(-50%);
		width: 36px;
		height: 5px;
		background: #D1D1D6;
		border-radius: 3px;
	}

	.close-btn {
		position: absolute;
		top: 12px;
		right: 12px;
		width: 36px;
		height: 36px;
		display: flex;
		align-items: center;
		justify-content: center;
		background: var(--gray-100, #f1f5f9);
		border: none;
		border-radius: 50%;
		color: var(--gray-500, #64748b);
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.close-btn:hover {
		background: var(--gray-200, #e2e8f0);
		color: var(--gray-700, #334155);
	}

	.modal-step {
		display: flex;
		flex-direction: column;
		align-items: center;
		text-align: center;
	}

	.icon-wrapper {
		width: 72px;
		height: 72px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 50%;
		margin-bottom: 16px;
		background: rgba(245, 158, 11, 0.1);
		color: #f59e0b;
	}

	.modal-title {
		font-family: var(--font-display, system-ui);
		font-size: 22px;
		font-weight: 700;
		color: var(--gray-900, #0f172a);
		margin: 0 0 8px;
	}

	.modal-description {
		font-size: 14px;
		color: var(--gray-500, #64748b);
		margin: 0 0 20px;
		line-height: 1.5;
	}

	.differences-list {
		width: 100%;
		background: var(--gray-50, #f8fafc);
		border-radius: 12px;
		padding: 12px;
		margin-bottom: 20px;
	}

	.difference-item {
		display: flex;
		flex-direction: column;
		gap: 4px;
		padding: 10px;
		border-radius: 8px;
		background: white;
	}

	.difference-item:not(:last-child) {
		margin-bottom: 8px;
	}

	.diff-label {
		font-size: 11px;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.05em;
		color: var(--gray-400, #9ca3af);
	}

	.diff-values {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.diff-old {
		flex: 1;
		font-size: 13px;
		color: var(--gray-500, #64748b);
		text-decoration: line-through;
		text-align: left;
		word-break: break-word;
	}

	:global(.diff-arrow) {
		color: var(--gray-300, #cbd5e1);
		flex-shrink: 0;
	}

	.diff-new {
		flex: 1;
		font-size: 13px;
		font-weight: 600;
		color: var(--gray-900, #0f172a);
		text-align: right;
		word-break: break-word;
	}

	.action-options {
		display: flex;
		flex-direction: column;
		gap: 10px;
		width: 100%;
		margin-bottom: 16px;
	}

	.option-btn {
		display: flex;
		align-items: center;
		gap: 12px;
		width: 100%;
		padding: 14px 16px;
		background: white;
		border: 2px solid var(--gray-100, #f1f5f9);
		border-radius: 12px;
		cursor: pointer;
		transition: all 0.2s ease;
		text-align: left;
	}

	.option-btn:hover:not(:disabled) {
		border-color: var(--gray-200, #e2e8f0);
		background: var(--gray-50, #f8fafc);
	}

	.option-btn.highlight {
		border-color: rgba(0, 102, 255, 0.2);
		background: rgba(0, 102, 255, 0.02);
	}

	.option-btn.highlight:hover:not(:disabled) {
		border-color: var(--blu-primary, #0066ff);
		background: rgba(0, 102, 255, 0.05);
	}

	.option-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.option-icon {
		width: 40px;
		height: 40px;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 10px;
		flex-shrink: 0;
	}

	.option-icon.keep {
		background: var(--gray-100, #f1f5f9);
		color: var(--gray-600, #475569);
	}

	.option-icon.use-new {
		background: rgba(245, 158, 11, 0.1);
		color: #f59e0b;
	}

	.option-icon.update {
		background: rgba(0, 102, 255, 0.1);
		color: var(--blu-primary, #0066ff);
	}

	.option-text {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.option-title {
		font-size: 15px;
		font-weight: 600;
		color: var(--gray-900, #0f172a);
	}

	.option-desc {
		font-size: 12px;
		color: var(--gray-500, #64748b);
	}

	.cancel-btn {
		padding: 12px 20px;
		background: transparent;
		border: none;
		color: var(--gray-500, #64748b);
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.cancel-btn:hover:not(:disabled) {
		color: var(--gray-700, #334155);
	}

	.cancel-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

</style>
