// apps/mobile/src/components/ui/Badge.tsx
import { View, Text } from 'react-native';

type BadgeVariant = 'default' | 'success' | 'warning' | 'error' | 'info';
type BadgeStatus = 'draft' | 'sent' | 'pending' | 'paid' | 'overdue' | 'signed';
type BadgeSize = 'sm' | 'md';

interface BadgeProps {
  children: string;
  variant?: BadgeVariant;
  status?: BadgeStatus;
  size?: BadgeSize;
  dot?: boolean;
}

const variantClasses: Record<BadgeVariant, { bg: string; text: string }> = {
  default: { bg: 'bg-gray-100', text: 'text-gray-700' },
  success: { bg: 'bg-emerald-50', text: 'text-emerald-700' },
  warning: { bg: 'bg-amber-50', text: 'text-amber-700' },
  error: { bg: 'bg-red-50', text: 'text-red-700' },
  info: { bg: 'bg-blue-50', text: 'text-blue-700' },
};

const STATUS_COLORS: Record<BadgeStatus, { bg: string; text: string; dot: string }> = {
  draft: { bg: '#F2F2F7', text: '#8E8E93', dot: '#8E8E93' },
  sent: { bg: '#E6F0FF', text: '#0066FF', dot: '#0066FF' },
  pending: { bg: 'rgba(245,158,11,0.1)', text: '#F59E0B', dot: '#F59E0B' },
  paid: { bg: '#E8FAE8', text: '#34C759', dot: '#34C759' },
  overdue: { bg: '#FFF0E6', text: '#FF9500', dot: '#FF9500' },
  signed: { bg: 'rgba(99,102,241,0.1)', text: '#6366F1', dot: '#6366F1' },
};

const SIZE_CLASSES: Record<BadgeSize, { container: string; text: string }> = {
  sm: { container: 'px-2 py-0.5', text: 'text-[10px]' },
  md: { container: 'px-2.5 py-1', text: 'text-xs' },
};

export function Badge({ children, variant = 'default', status, size = 'md', dot }: BadgeProps) {
  const sizeStyle = SIZE_CLASSES[size];

  if (status) {
    const colors = STATUS_COLORS[status];
    return (
      <View
        className={`rounded-chip flex-row items-center gap-1.5 ${sizeStyle.container}`}
        style={{ backgroundColor: colors.bg }}
      >
        {dot && (
          <View
            className="w-1.5 h-1.5 rounded-full"
            style={{ backgroundColor: colors.dot }}
          />
        )}
        <Text className={`font-semibold capitalize ${sizeStyle.text}`} style={{ color: colors.text }}>
          {children}
        </Text>
      </View>
    );
  }

  const { bg, text } = variantClasses[variant];

  return (
    <View className={`rounded-chip ${bg} ${sizeStyle.container}`}>
      <Text className={`font-medium ${text} ${sizeStyle.text}`}>{children}</Text>
    </View>
  );
}

// src/lib/components/ui/Badge.svelte
<script lang="ts">
	interface Props {
		status?: 'draft' | 'sent' | 'pending' | 'paid' | 'overdue' | 'signed';
		variant?: 'default' | 'outline' | 'dot';
		size?: 'sm' | 'md';
		class?: string;
		children?: import('svelte').Snippet;
	}

	let {
		status,
		variant = 'default',
		size = 'md',
		class: className = '',
		children
	}: Props = $props();

	const statusLabels: Record<string, string> = {
		draft: 'Draft',
		sent: 'Sent',
		pending: 'Pending',
		paid: 'Paid',
		overdue: 'Overdue',
		signed: 'Signed'
	};

	const statusClasses: Record<string, string> = {
		draft: 'badge-draft',
		sent: 'badge-sent',
		pending: 'badge-pending',
		paid: 'badge-paid',
		overdue: 'badge-overdue',
		signed: 'badge-signed'
	};
</script>

<span
	class="badge {variant} {size === 'sm' ? 'badge-sm' : ''} {status
		? statusClasses[status]
		: ''} {className}"
>
	{#if variant === 'dot'}
		<span class="badge-dot"></span>
	{/if}
	{#if children}
		{@render children()}
	{:else if status}
		{statusLabels[status]}
	{/if}
</span>

<style>
	.badge {
		display: inline-flex;
		align-items: center;
		gap: 6px;
		padding: 6px 12px;
		font-size: 12px;
		font-weight: 600;
		border-radius: var(--radius-chip, 100px);
		white-space: nowrap;
		transition: all 0.2s ease;
	}

	.badge-sm {
		padding: 4px 8px;
		font-size: 11px;
	}

	/* Status colors - Apple HIG aligned */
	.badge-draft {
		background: #F2F2F7;
		color: #8E8E93;
	}

	.badge-sent {
		background: #E6F0FF;
		color: #0066FF;
	}

	.badge-pending {
		background: var(--status-pending-bg, rgba(245, 158, 11, 0.1));
		color: var(--status-pending, #f59e0b);
	}

	.badge-paid {
		background: #E8FAE8;
		color: #34C759;
	}

	.badge-overdue {
		background: #FFF0E6;
		color: #FF9500;
	}

	.badge-signed {
		background: var(--status-signed-bg, rgba(99, 102, 241, 0.1));
		color: var(--status-signed, #6366f1);
	}

	/* Outline variant */
	.badge.outline {
		background: transparent;
		border: 1px solid currentColor;
	}

	.badge.outline.badge-draft {
		border-color: var(--gray-300, #cbd5e1);
	}

	/* Dot variant */
	.badge.dot {
		background: transparent;
		padding: 4px 0;
	}

	.badge-dot {
		width: 8px;
		height: 8px;
		border-radius: 50%;
		background: currentColor;
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.badge {
			transition: none;
		}
	}
</style>
