// apps/web/src/components/landing/HeroHeadline.tsx
import { useState, useEffect, useMemo } from 'preact/hooks';
import { useI18nStore } from '@/lib/i18n';

interface Word {
	text: string;
	highlight?: boolean;
}

interface HeroHeadlineProps {
	words?: Word[];
}

const styles = {
	container: {
		textAlign: 'center' as const,
		position: 'relative' as const,
		transition: 'opacity 0.6s cubic-bezier(0.16, 1, 0.3, 1), transform 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
		transitionDelay: '0.1s',
	},
	headline: {
		fontFamily: 'var(--font-display)',
		fontSize: 'clamp(2.5rem, 8vw, 5rem)',
		fontWeight: 700,
		lineHeight: 1.1,
		letterSpacing: '-0.03em',
		color: 'var(--gray-900, #0f172a)',
		margin: '0 0 24px 0',
	},
	word: {
		display: 'inline-block',
	},
	highlight: {
		display: 'inline-block',
		background: 'linear-gradient(135deg, #0066ff 0%, #0ea5e9 50%, #6366f1 100%)',
		WebkitBackgroundClip: 'text',
		WebkitTextFillColor: 'transparent',
		backgroundClip: 'text',
	},
	subheadline: {
		fontFamily: 'var(--font-body)',
		fontSize: 'clamp(1rem, 2.5vw, 1.25rem)',
		fontWeight: 400,
		lineHeight: 1.6,
		color: 'var(--gray-600, #475569)',
		maxWidth: 540,
		margin: '0 auto',
	},
};

export function HeroHeadline({ words: wordsProp }: HeroHeadlineProps) {
	const { t } = useI18nStore();
	const [visible, setVisible] = useState(false);

	const words = useMemo(
		() =>
			wordsProp ?? [
				{ text: t('landing.hero.word1') },
				{ text: t('landing.hero.word2'), highlight: true },
				{ text: t('landing.hero.word3') },
			],
		[wordsProp, t]
	);

	const subheadline = useMemo(() => t('landing.hero.subheadline'), [t]);

	useEffect(() => {
		requestAnimationFrame(() => {
			setVisible(true);
		});
	}, []);

	const containerStyle = {
		...styles.container,
		opacity: visible ? 1 : 0,
		transform: visible ? 'translateY(0)' : 'translateY(16px)',
	};

	return (
		<div style={containerStyle}>
			<h1 style={styles.headline}>
				{words.map((word, wordIndex) => (
					<>
						<span
							key={word.text}
							style={word.highlight ? styles.highlight : styles.word}
						>
							{word.text}
						</span>
						{wordIndex < words.length - 1 && (
							<span style={{ display: 'inline' }}>&nbsp;</span>
						)}
					</>
				))}
			</h1>
			<p style={styles.subheadline}>{subheadline}</p>
		</div>
	);
}

// src/lib/components/landing/Hero/HeroHeadline.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { t } from '$lib/i18n';

	let {
		words: wordsProp
	}: {
		words?: { text: string; highlight?: boolean }[];
	} = $props();

	// Reactive: use prop if provided, otherwise derive from translations
	const words = $derived(
		wordsProp ?? [
			{ text: $t('landing.hero.word1') },
			{ text: $t('landing.hero.word2'), highlight: true },
			{ text: $t('landing.hero.word3') }
		]
	);

	const subheadline = $derived($t('landing.hero.subheadline'));

	let visible = $state(false);

	onMount(() => {
		// Small delay before starting animation
		requestAnimationFrame(() => {
			visible = true;
		});
	});
</script>

<div class="hero-headline-container" class:visible>
	<h1 class="hero-headline">
		{#each words as word, wordIndex (word.text)}
			<span class="word" class:highlight={word.highlight}>
				{word.text}
			</span>
			{#if wordIndex < words.length - 1}
				<span class="word-space">&nbsp;</span>
			{/if}
		{/each}
	</h1>

	<p class="hero-subheadline">
		{subheadline}
	</p>
</div>

<style>
	.hero-headline-container {
		text-align: center;
		position: relative;
		opacity: 0;
		transform: translateY(16px);
		transition:
			opacity 0.6s cubic-bezier(0.16, 1, 0.3, 1),
			transform 0.6s cubic-bezier(0.16, 1, 0.3, 1);
		transition-delay: 0.1s;
	}

	.hero-headline-container.visible {
		opacity: 1;
		transform: translateY(0);
	}

	.hero-headline {
		font-family: var(--font-display);
		font-size: clamp(2.5rem, 8vw, 5rem);
		font-weight: 700;
		line-height: 1.1;
		letter-spacing: -0.03em;
		color: var(--gray-900, #0f172a);
		margin: 0 0 24px 0;
	}

	.word {
		display: inline-block;
	}

	.word.highlight {
		background: linear-gradient(135deg, #0066ff 0%, #0ea5e9 50%, #6366f1 100%);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}

	.word-space {
		display: inline;
	}

	.hero-subheadline {
		font-family: var(--font-body);
		font-size: clamp(1rem, 2.5vw, 1.25rem);
		font-weight: 400;
		line-height: 1.6;
		color: var(--gray-600, #475569);
		max-width: 540px;
		margin: 0 auto;
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.hero-headline-container {
			opacity: 1;
			transform: none;
			transition: none;
		}
	}

	/* Mobile adjustments */
	@media (max-width: 640px) {
		.hero-headline {
			margin-bottom: 20px;
		}

		.hero-subheadline {
			padding: 0 16px;
		}
	}
</style>
