// apps/web/src/components/tutorial/TutorialProvider.tsx
import { useEffect, useState } from 'preact/hooks';
import { useTutorialStore } from '@/stores/tutorialStore';
import { TutorialStartModal } from './TutorialStartModal';
import { TutorialOverlay } from './TutorialOverlay';
import { TutorialCompleteModal } from './TutorialCompleteModal';
import { HintTooltip } from './HintTooltip';

export function TutorialProvider() {
  const initialize = useTutorialStore((s) => s.initialize);
  const [isOnDashboard, setIsOnDashboard] = useState(false);

  useEffect(() => {
    setIsOnDashboard(window.location.pathname.startsWith('/dashboard'));

    // Small delay to let the page fully render
    const timer = setTimeout(() => {
      initialize();
    }, 500);

    return () => clearTimeout(timer);
  }, []);

  if (!isOnDashboard) return null;

  return (
    <>
      <TutorialStartModal />
      <TutorialOverlay />
      <TutorialCompleteModal />
      <HintTooltip />
    </>
  );
}

// src/lib/tutorial/components/TutorialProvider.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { tutorialStore } from '../store.svelte';
	import TutorialStartModal from './TutorialStartModal.svelte';
	import TutorialOverlay from './TutorialOverlay.svelte';
	import TutorialCompleteModal from './TutorialCompleteModal.svelte';
	import HintTooltip from './HintTooltip.svelte';

	// Initialize tutorial on mount
	onMount(() => {
		// Small delay to let the page fully render
		const timer = setTimeout(() => {
			tutorialStore.initialize();
		}, 500);

		return () => clearTimeout(timer);
	});

	// Check if user is on dashboard (required for tutorial)
	const isOnDashboard = $derived($page.url.pathname.startsWith('/dashboard'));
</script>

<!-- Only show tutorial components when on dashboard -->
{#if isOnDashboard}
	<TutorialStartModal />
	<TutorialOverlay />
	<TutorialCompleteModal />
	<HintTooltip />
{/if}
