// src/routes/dashboard/review/components/TransformClientSelector.svelte
<script lang="ts">
	import Search from 'lucide-svelte/icons/search';
	import Loader2 from 'lucide-svelte/icons/loader-2';
	import User from 'lucide-svelte/icons/user';
	import Sparkles from 'lucide-svelte/icons/sparkles';
	import ChevronLeft from 'lucide-svelte/icons/chevron-left';
	import { t } from '$lib/i18n';

	interface ClientSuggestion {
		id: string;
		name: string;
		estimateCount: number;
		invoiceCount: number;
		similarity: number;
	}

	interface Props {
		suggestions: ClientSuggestion[];
		bestMatch: ClientSuggestion | null;
		searchedDocType: string | null;
		manualSearchQuery: string;
		manualSearchResults: ClientSuggestion[];
		isSearching: boolean;
		onSelectClient: (name: string) => void;
		onSearch: (query: string) => void;
		onBack: () => void;
	}

	let {
		suggestions,
		bestMatch,
		searchedDocType,
		manualSearchQuery = $bindable(),
		manualSearchResults,
		isSearching,
		onSelectClient,
		onSearch,
		onBack
	}: Props = $props();

	function hasRelevantDocs(client: ClientSuggestion): boolean {
		if (searchedDocType === 'estimate') return client.estimateCount > 0;
		if (searchedDocType === 'invoice') return client.invoiceCount > 0;
		return client.estimateCount > 0 || client.invoiceCount > 0;
	}

	const otherSuggestions = $derived(
		bestMatch ? suggestions.filter((s) => s.id !== bestMatch?.id) : suggestions
	);
</script>

<div class="client-select-card">
	<div class="client-search-box">
		<Search size={18} class="search-icon" />
		<input
			type="text"
			placeholder={$t('placeholder.searchClients')}
			bind:value={manualSearchQuery}
			oninput={() => onSearch(manualSearchQuery)}
		/>
		{#if isSearching}
			<Loader2 size={18} class="spinning" />
		{/if}
	</div>

	<div class="client-list">
		{#if manualSearchResults.length > 0}
			{#each manualSearchResults as client (client.id)}
				<button class="client-option" onclick={() => onSelectClient(client.name)}>
					<User size={16} />
					<span class="client-name">{client.name}</span>
					<span class="match-percent">{Math.round(client.similarity * 100)}%</span>
				</button>
			{/each}
		{:else if bestMatch}
			{@const bestHasDocs = hasRelevantDocs(bestMatch)}
			<button
				class="client-option best"
				class:disabled={!bestHasDocs}
				onclick={() => bestHasDocs && onSelectClient(bestMatch.name)}
				disabled={!bestHasDocs}
			>
				<Sparkles size={16} />
				<span class="client-name">{bestMatch.name}</span>
				<span class="match-percent best">{Math.round(bestMatch.similarity * 100)}%</span>
			</button>
			{#each otherSuggestions.slice(0, 4) as client (client.id)}
				{@const clientHasDocs = hasRelevantDocs(client)}
				<button
					class="client-option"
					class:disabled={!clientHasDocs}
					onclick={() => clientHasDocs && onSelectClient(client.name)}
					disabled={!clientHasDocs}
				>
					<User size={16} />
					<span class="client-name">{client.name}</span>
					<span class="match-percent">{Math.round(client.similarity * 100)}%</span>
				</button>
			{/each}
		{:else if suggestions.length > 0}
			{#each suggestions.slice(0, 5) as client (client.id)}
				{@const clientHasDocs = hasRelevantDocs(client)}
				<button
					class="client-option"
					class:disabled={!clientHasDocs}
					onclick={() => clientHasDocs && onSelectClient(client.name)}
					disabled={!clientHasDocs}
				>
					<User size={16} />
					<span class="client-name">{client.name}</span>
					<span class="match-percent">{Math.round(client.similarity * 100)}%</span>
				</button>
			{/each}
		{:else}
			<div class="empty-state">
				<p>{$t('review.noClientsFound')}</p>
			</div>
		{/if}
	</div>
</div>

<div class="action-buttons">
	<button class="btn secondary" onclick={onBack}>
		<ChevronLeft size={18} />
		Back
	</button>
</div>

<style>
	.client-select-card {
		background: var(--white);
		border-radius: var(--radius-lg);
		border: 1px solid var(--gray-200);
		overflow: hidden;
		margin-bottom: var(--space-4);
	}

	.client-search-box {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-3) var(--space-4);
		border-bottom: 1px solid var(--gray-100);
	}

	.client-search-box :global(.search-icon) {
		color: var(--gray-400);
		flex-shrink: 0;
	}

	.client-search-box input {
		flex: 1;
		border: none;
		outline: none;
		font-size: var(--text-base);
		background: transparent;
		color: var(--gray-900);
	}

	.client-search-box input::placeholder {
		color: var(--gray-400);
	}

	.client-search-box :global(.spinning) {
		color: var(--blu-primary);
	}

	.client-list {
		max-height: 280px;
		overflow-y: auto;
	}

	.client-option {
		width: 100%;
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-3) var(--space-4);
		background: transparent;
		border: none;
		border-bottom: 1px solid var(--gray-100);
		cursor: pointer;
		transition: background var(--duration-fast) ease;
		text-align: left;
	}

	.client-option:last-child {
		border-bottom: none;
	}

	.client-option:hover:not(.disabled) {
		background: var(--gray-50);
	}

	.client-option.best {
		background: var(--glass-primary-5);
	}

	.client-option.best:hover:not(.disabled) {
		background: var(--glass-primary-10);
	}

	.client-option.disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.client-option :global(svg) {
		color: var(--gray-400);
		flex-shrink: 0;
	}

	.client-option.best :global(svg) {
		color: var(--blu-primary);
	}

	.client-option .client-name {
		flex: 1;
		font-size: var(--text-base);
		font-weight: var(--font-medium);
		color: var(--gray-900);
	}

	.client-option .match-percent {
		font-size: var(--text-sm);
		font-weight: var(--font-medium);
		color: var(--gray-500);
	}

	.client-option .match-percent.best {
		color: var(--data-green);
	}

	.client-list .empty-state {
		padding: var(--space-6);
		text-align: center;
		color: var(--gray-500);
	}

	.action-buttons {
		display: flex;
		gap: var(--space-3);
	}

	.action-buttons .btn {
		display: flex;
		align-items: center;
		gap: var(--space-2);
	}

	.btn {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 14px 24px;
		border-radius: 14px;
		font-size: 15px;
		font-weight: 600;
		transition: all 0.2s ease;
	}

	.btn.secondary {
		background: transparent;
		border: 1px solid var(--gray-200);
		color: var(--gray-600);
	}

	:global(.spinning) {
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>

// apps/web/src/components/review/TransformClientSelector.tsx
import { useMemo } from 'preact/hooks';
import { Search, Loader2, User, Sparkles, ChevronLeft } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useI18nStore } from '@/lib/i18n';
import type { TransformClientSuggestion } from '@/lib/review/review-types';

interface TransformClientSelectorProps {
  suggestions: TransformClientSuggestion[];
  bestMatch: TransformClientSuggestion | null;
  searchedDocType: string | null;
  manualSearchQuery: string;
  onManualSearchQueryChange: (value: string) => void;
  manualSearchResults: TransformClientSuggestion[];
  isSearching: boolean;
  onSelectClient: (name: string) => void;
  onSearch: (query: string) => void;
  onBack: () => void;
}

function hasRelevantDocs(client: TransformClientSuggestion, searchedDocType: string | null): boolean {
  if (searchedDocType === 'estimate') return client.estimateCount > 0;
  if (searchedDocType === 'invoice') return client.invoiceCount > 0;
  return client.estimateCount > 0 || client.invoiceCount > 0;
}

export function TransformClientSelector({
  suggestions,
  bestMatch,
  searchedDocType,
  manualSearchQuery,
  onManualSearchQueryChange,
  manualSearchResults,
  isSearching,
  onSelectClient,
  onSearch,
  onBack,
}: TransformClientSelectorProps) {
  const { t } = useI18nStore();

  const otherSuggestions = useMemo(
    () => (bestMatch ? suggestions.filter((s) => s.id !== bestMatch.id) : suggestions),
    [bestMatch, suggestions]
  );

  function handleSearchInput(e: Event) {
    const value = (e.currentTarget as HTMLInputElement).value;
    onManualSearchQueryChange(value);
    onSearch(value);
  }

  return (
    <>
      <style>{`@keyframes tcsSpin { to { transform: rotate(360deg); } } .tcs-spinning { animation: tcsSpin 1s linear infinite; }`}</style>
      <div class="bg-[var(--white)] rounded-[var(--radius-lg)] border border-[var(--gray-200)] overflow-hidden mb-[var(--space-4)]">
        <div class="flex items-center gap-[var(--space-3)] px-[var(--space-4)] py-[var(--space-3)] border-b border-[var(--gray-100)]">
          <Search size={18} class="text-[var(--gray-400)] shrink-0" />
          <input
            type="text"
            placeholder={t('placeholder.searchClients')}
            value={manualSearchQuery}
            onInput={handleSearchInput}
            class="flex-1 border-none outline-none text-[var(--text-base)] bg-transparent text-[var(--gray-900)]"
          />
          {isSearching && <Loader2 size={18} class="tcs-spinning text-[var(--blu-primary)]" />}
        </div>

        <div class="max-h-[280px] overflow-y-auto">
          {manualSearchResults.length > 0 ? (
            manualSearchResults.map((client) => (
              <button
                key={client.id}
                class="w-full flex items-center gap-[var(--space-3)] px-[var(--space-4)] py-[var(--space-3)] bg-transparent border-none border-b border-[var(--gray-100)] cursor-pointer transition-[background] duration-150 text-left hover:bg-[var(--gray-50)]"
                onClick={() => onSelectClient(client.name)}
              >
                <User size={16} class="text-[var(--gray-400)] shrink-0" />
                <span class="flex-1 text-[var(--text-base)] font-[var(--font-medium)] text-[var(--gray-900)]">
                  {client.name}
                </span>
                <span class="text-[var(--text-sm)] font-[var(--font-medium)] text-[var(--gray-500)]">
                  {Math.round(client.similarity * 100)}%
                </span>
              </button>
            ))
          ) : bestMatch ? (
            <>
              {(() => {
                const bestHasDocs = hasRelevantDocs(bestMatch, searchedDocType);
                return (
                  <button
                    class={cn(
                      'w-full flex items-center gap-[var(--space-3)] px-[var(--space-4)] py-[var(--space-3)] border-none border-b border-[var(--gray-100)] text-left transition-[background] duration-150 bg-[var(--glass-primary-5)]',
                      bestHasDocs ? 'cursor-pointer hover:bg-[var(--gray-50)]' : 'opacity-50 cursor-not-allowed'
                    )}
                    onClick={() => bestHasDocs && onSelectClient(bestMatch.name)}
                    disabled={!bestHasDocs}
                  >
                    <Sparkles size={16} class="text-[var(--blu-primary)] shrink-0" />
                    <span class="flex-1 text-[var(--text-base)] font-[var(--font-medium)] text-[var(--gray-900)]">
                      {bestMatch.name}
                    </span>
                    <span class="text-[var(--text-sm)] font-[var(--font-medium)] text-[var(--data-green)]">
                      {Math.round(bestMatch.similarity * 100)}%
                    </span>
                  </button>
                );
              })()}
              {otherSuggestions.slice(0, 4).map((client) => {
                const clientHasDocs = hasRelevantDocs(client, searchedDocType);
                return (
                  <button
                    key={client.id}
                    class={cn(
                      'w-full flex items-center gap-[var(--space-3)] px-[var(--space-4)] py-[var(--space-3)] bg-transparent border-none border-b border-[var(--gray-100)] text-left transition-[background] duration-150',
                      clientHasDocs ? 'cursor-pointer hover:bg-[var(--gray-50)]' : 'opacity-50 cursor-not-allowed'
                    )}
                    onClick={() => clientHasDocs && onSelectClient(client.name)}
                    disabled={!clientHasDocs}
                  >
                    <User size={16} class="text-[var(--gray-400)] shrink-0" />
                    <span class="flex-1 text-[var(--text-base)] font-[var(--font-medium)] text-[var(--gray-900)]">
                      {client.name}
                    </span>
                    <span class="text-[var(--text-sm)] font-[var(--font-medium)] text-[var(--gray-500)]">
                      {Math.round(client.similarity * 100)}%
                    </span>
                  </button>
                );
              })}
            </>
          ) : suggestions.length > 0 ? (
            suggestions.slice(0, 5).map((client) => {
              const clientHasDocs = hasRelevantDocs(client, searchedDocType);
              return (
                <button
                  key={client.id}
                  class={cn(
                    'w-full flex items-center gap-[var(--space-3)] px-[var(--space-4)] py-[var(--space-3)] bg-transparent border-none border-b border-[var(--gray-100)] text-left transition-[background] duration-150',
                    clientHasDocs ? 'cursor-pointer hover:bg-[var(--gray-50)]' : 'opacity-50 cursor-not-allowed'
                  )}
                  onClick={() => clientHasDocs && onSelectClient(client.name)}
                  disabled={!clientHasDocs}
                >
                  <User size={16} class="text-[var(--gray-400)] shrink-0" />
                  <span class="flex-1 text-[var(--text-base)] font-[var(--font-medium)] text-[var(--gray-900)]">
                    {client.name}
                  </span>
                  <span class="text-[var(--text-sm)] font-[var(--font-medium)] text-[var(--gray-500)]">
                    {Math.round(client.similarity * 100)}%
                  </span>
                </button>
              );
            })
          ) : (
            <div class="p-[var(--space-6)] text-center text-[var(--gray-500)]">
              <p>{t('review.noClientsFound')}</p>
            </div>
          )}
        </div>
      </div>

      <div class="flex gap-[var(--space-3)]">
        <button
          class="flex items-center gap-2 px-6 py-3.5 rounded-[14px] text-[15px] font-semibold transition-all duration-200 cursor-pointer bg-transparent border border-[var(--gray-200)] text-[var(--gray-600)] hover:bg-[var(--gray-100)]"
          onClick={onBack}
        >
          <ChevronLeft size={18} />
          Back
        </button>
      </div>
    </>
  );
}
