// apps/mobile/src/components/modals/ShareLinkModal.tsx
import { useState, useEffect, useCallback } from 'react';
import { View, Text, Modal, Pressable, ActivityIndicator } from 'react-native';
import { Link, Copy, Check, ExternalLink, HelpCircle, X } from 'lucide-react-native';
import * as Clipboard from 'expo-clipboard';
import * as Linking from 'expo-linking';
import { useI18nStore } from '@/lib/i18n';
import { useToastStore } from '@/stores/toastStore';
import { Button } from '@/components/ui/Button';

interface ShareLinkModalProps {
  visible: boolean;
  onClose: () => void;
  shareUrl: string | null;
  documentType?: 'invoice' | 'estimate' | 'contract';
}

export function ShareLinkModal({
  visible,
  onClose,
  shareUrl,
  documentType = 'invoice',
}: ShareLinkModalProps) {
  const { t } = useI18nStore();
  const toast = useToastStore();
  const [isCopied, setIsCopied] = useState(false);

  const isLoading = !shareUrl;

  useEffect(() => {
    if (visible) setIsCopied(false);
  }, [visible]);

  const handleCopy = useCallback(async () => {
    if (!shareUrl) return;
    try {
      await Clipboard.setStringAsync(shareUrl);
      setIsCopied(true);
      toast.success(t('common.copied'));
      setTimeout(() => setIsCopied(false), 3000);
    } catch {
      toast.error('Failed to copy link');
    }
  }, [shareUrl, t, toast]);

  const handleOpenInBrowser = useCallback(async () => {
    if (!shareUrl) return;
    try {
      await Linking.openURL(shareUrl);
    } catch {
      toast.error('Failed to open link');
    }
  }, [shareUrl, toast]);

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onClose}
      statusBarTranslucent
    >
      {/* Backdrop */}
      <Pressable
        className="flex-1 bg-black/50 items-center justify-center px-6"
        onPress={onClose}
      >
        {/* Modal content */}
        <Pressable className="w-full max-w-sm" onPress={() => {}}>
          <View className="bg-white rounded-2xl p-6">
            {/* Close button */}
            <Pressable
              className="absolute top-4 right-4 p-1 z-10"
              onPress={onClose}
              hitSlop={8}
            >
              <X size={20} color="#64748B" />
            </Pressable>

            {/* Header */}
            <View className="flex-row items-center gap-3 mb-4">
              <Link size={24} color="#3B82F6" />
              <Text className="text-lg font-semibold text-gray-900">
                {t('review.shareLinkCreated')}
              </Text>
            </View>

            {/* Body */}
            {isLoading ? (
              <View className="items-center py-8">
                <ActivityIndicator size="large" color="#0066FF" />
                <Text className="text-sm text-gray-500 mt-3">Generating link...</Text>
              </View>
            ) : (
              <View className="gap-4">
                {/* Description */}
                <Text className="text-sm text-gray-500">
                  {t('review.anyoneCanView', { type: documentType })}
                </Text>

                {/* Link display */}
                <View className="bg-gray-50 rounded-lg border border-gray-200 px-3 py-3">
                  <Text className="text-[13px] text-gray-900 font-mono" numberOfLines={2}>
                    {shareUrl}
                  </Text>
                </View>

                {/* Actions */}
                <View className="flex-row gap-2.5">
                  <View className="flex-1">
                    <Button
                      onPress={handleCopy}
                      variant="secondary"
                      size="md"
                      fullWidth
                      icon={
                        isCopied
                          ? <Check size={16} color="#059669" />
                          : <Copy size={16} color="#475569" />
                      }
                    >
                      {isCopied ? t('common.copied') : t('review.copyLink')}
                    </Button>
                  </View>
                  <View className="flex-1">
                    <Button
                      onPress={handleOpenInBrowser}
                      variant="primary"
                      size="md"
                      fullWidth
                      icon={<ExternalLink size={16} color="#FFFFFF" />}
                    >
                      {t('review.openPreview')}
                    </Button>
                  </View>
                </View>
              </View>
            )}

            {/* Footer note */}
            <View className="flex-row items-center gap-1.5 mt-4 pt-4 border-t border-gray-100">
              <HelpCircle size={14} color="#94A3B8" />
              <Text className="text-xs text-gray-400">
                {t('review.noLoginRequired')}
              </Text>
            </View>
          </View>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

// src/routes/dashboard/review/components/ShareLinkModal.svelte
<script lang="ts">
	import { t } from '$lib/i18n';
	import X from 'lucide-svelte/icons/x';
	import Link from 'lucide-svelte/icons/link';
	import Copy from 'lucide-svelte/icons/copy';
	import Check from 'lucide-svelte/icons/check';
	import ExternalLink from 'lucide-svelte/icons/external-link';
	import HelpCircle from 'lucide-svelte/icons/help-circle';

	interface Props {
		open: boolean;
		linkUrl: string | null;
		documentType: 'invoice' | 'estimate';
		onClose: () => void;
	}

	let { open, linkUrl, documentType, onClose }: Props = $props();

	let copied = $state(false);

	async function copyLink() {
		if (linkUrl) {
			try {
				await navigator.clipboard.writeText(linkUrl);
				copied = true;
				setTimeout(() => (copied = false), 3000);
			} catch {
				console.error('Failed to copy link');
			}
		}
	}

	function openPreview() {
		if (linkUrl) {
			window.open(linkUrl, '_blank');
		}
	}
</script>

{#if open}
	<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
	<div class="modal-overlay" onclick={onClose} role="presentation">
		<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions a11y_interactive_supports_focus -->
		<div
			class="modal-content view-link-modal"
			onclick={(e) => e.stopPropagation()}
			role="dialog"
			aria-modal="true"
			tabindex="-1"
		>
			<button class="modal-close" onclick={onClose}>
				<X size={20} />
			</button>

			<div class="modal-header">
				<Link size={24} class="modal-icon" />
				<h3>{$t('review.shareLinkCreated')}</h3>
			</div>

			<div class="modal-body">
				<p class="modal-description">{$t('review.anyoneCanView', { type: documentType })}</p>

				<div class="link-display">
					<input type="text" readonly value={linkUrl || ''} class="link-input" />
				</div>

				<div class="modal-actions">
					<button class="modal-btn secondary" onclick={copyLink}>
						{#if copied}
							<Check size={16} />
							{$t('common.copied')}
						{:else}
							<Copy size={16} />
							{$t('review.copyLink')}
						{/if}
					</button>
					<button class="modal-btn primary" onclick={openPreview}>
						<ExternalLink size={16} />
						{$t('review.openPreview')}
					</button>
				</div>
			</div>

			<p class="modal-footer-note">
				<HelpCircle size={14} />
				{$t('review.noLoginRequired')}
			</p>
		</div>
	</div>
{/if}

<style>
	/* View Link Modal */
	.modal-overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
		padding: 20px;
	}

	.modal-content {
		background: var(--white);
		border-radius: 16px;
		padding: 24px;
		max-width: 480px;
		width: 100%;
		position: relative;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
	}

	.modal-close {
		position: absolute;
		top: 16px;
		right: 16px;
		background: none;
		border: none;
		color: var(--gray-500);
		cursor: pointer;
		padding: 4px;
		border-radius: 6px;
		transition: all 0.15s ease;
	}

	.modal-close:hover {
		background: var(--gray-100);
		color: #334155;
	}

	.modal-header {
		display: flex;
		align-items: center;
		gap: 12px;
		margin-bottom: 16px;
	}

	.modal-header :global(.modal-icon) {
		color: #3b82f6;
	}

	.modal-header h3 {
		font-size: 18px;
		font-weight: 600;
		color: #1e293b;
		margin: 0;
	}

	.modal-body {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.modal-description {
		font-size: 14px;
		color: var(--gray-500);
		margin: 0;
	}

	.link-display {
		background: transparent;
		border: 1px solid var(--gray-200);
		border-radius: 8px;
		padding: 4px;
	}

	.link-input {
		width: 100%;
		border: none;
		background: transparent;
		padding: 10px 12px;
		font-size: 13px;
		color: #1e293b;
		font-family: ui-monospace, monospace;
	}

	.link-input:focus {
		outline: none;
	}

	.modal-actions {
		display: flex;
		gap: 10px;
	}

	.modal-btn {
		flex: 1;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 8px;
		padding: 12px 16px;
		border-radius: 10px;
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.modal-btn.secondary {
		background: var(--gray-100);
		border: 1px solid var(--gray-200);
		color: var(--gray-600);
	}

	.modal-btn.secondary:hover {
		background: var(--gray-200);
	}

	.modal-btn.primary {
		background: #3b82f6;
		border: none;
		color: white;
	}

	.modal-btn.primary:hover {
		background: #2563eb;
	}

	.modal-footer-note {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 12px;
		color: var(--gray-400);
		margin: 16px 0 0;
		padding-top: 16px;
		border-top: 1px solid #f1f5f9;
	}
</style>
