// src/lib/components/forms/FormSection.svelte
<script lang="ts">
	interface Props {
		title?: string;
		description?: string;
		variant?: 'default' | 'card' | 'inline';
		class?: string;
		children?: import('svelte').Snippet;
	}

	let {
		title,
		description,
		variant = 'default',
		class: className = '',
		children
	}: Props = $props();
</script>

<section class="form-section {variant} {className}">
	{#if title || description}
		<div class="section-header">
			{#if title}
				<h3 class="section-title">{title}</h3>
			{/if}
			{#if description}
				<p class="section-description">{description}</p>
			{/if}
		</div>
	{/if}

	<div class="section-content">
		{#if children}
			{@render children()}
		{/if}
	</div>
</section>

<style>
	.form-section {
		display: flex;
		flex-direction: column;
		gap: 20px;
	}

	/* Card variant - glass/transparent background */
	.form-section.card {
		background: rgba(255, 255, 255, 0.4);
		backdrop-filter: blur(12px);
		-webkit-backdrop-filter: blur(12px);
		border: 1px solid rgba(255, 255, 255, 0.5);
		border-radius: var(--radius-card, 20px);
		padding: var(--card-padding, 20px);
	}

	/* Inline variant */
	.form-section.inline {
		flex-direction: row;
		align-items: flex-start;
		gap: 24px;
	}

	.form-section.inline .section-header {
		flex: 0 0 200px;
	}

	.form-section.inline .section-content {
		flex: 1;
	}

	@media (max-width: 640px) {
		.form-section.inline {
			flex-direction: column;
			gap: 16px;
		}

		.form-section.inline .section-header {
			flex: none;
		}
	}

	/* Header */
	.section-header {
		display: flex;
		flex-direction: column;
		gap: 4px;
	}

	.section-title {
		font-family: var(--font-display, system-ui);
		font-size: 16px;
		font-weight: 600;
		color: var(--gray-900, #0f172a);
		margin: 0;
		letter-spacing: -0.01em;
	}

	.section-description {
		font-size: 13px;
		color: var(--gray-500, #64748b);
		margin: 0;
		line-height: 1.5;
	}

	/* Content */
	.section-content {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}
</style>

// apps/web/src/components/forms/FormSection.tsx
import type { ComponentChildren } from 'preact';

type SectionVariant = 'default' | 'card' | 'inline';

interface FormSectionProps {
  title?: string;
  description?: string;
  variant?: SectionVariant;
  className?: string;
  children: ComponentChildren;
}

const styles = {
  base: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  card: {
    padding: '24px',
    borderRadius: 'var(--radius-md, 12px)',
    border: '1px solid var(--gray-200)',
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
  },
  inline: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start',
    gap: '32px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  },
  inlineHeader: {
    minWidth: '200px',
    maxWidth: '280px',
    flexShrink: 0,
  },
  title: {
    fontSize: 17,
    fontWeight: 600,
    color: 'var(--gray-900)',
    lineHeight: 1.4,
  },
  description: {
    fontSize: 14,
    color: 'var(--gray-500)',
    lineHeight: 1.5,
  },
  content: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    flex: 1,
    minWidth: 0,
  },
};

export function FormSection({
  title,
  description,
  variant = 'default',
  className,
  children,
}: FormSectionProps) {
  const isCard = variant === 'card';
  const isInline = variant === 'inline';

  const sectionStyle: Record<string, string | number> = {
    ...styles.base,
    ...(isCard ? styles.card : {}),
    ...(isInline ? styles.inline : {}),
  };

  const hasHeader = title || description;

  return (
    <div style={sectionStyle} class={className}>
      {hasHeader && (
        <div style={{ ...styles.header, ...(isInline ? styles.inlineHeader : {}) }}>
          {title && <h3 style={styles.title}>{title}</h3>}
          {description && <p style={styles.description}>{description}</p>}
        </div>
      )}

      <div style={styles.content}>{children}</div>
    </div>
  );
}
