// src/lib/components/forms/FormToggle.svelte
<script lang="ts">
	interface Props {
		label: string;
		description?: string;
		name?: string;
		checked?: boolean;
		disabled?: boolean;
		size?: 'sm' | 'md';
		variant?: 'default' | 'card';
		class?: string;
		onchange?: (checked: boolean) => void;
	}

	let {
		label,
		description,
		name,
		checked = $bindable(false),
		disabled = false,
		size = 'md',
		variant = 'default',
		class: className = '',
		onchange
	}: Props = $props();

	function handleChange() {
		if (disabled) return;
		checked = !checked;
		onchange?.(checked);
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleChange();
		}
	}
</script>

<div
	class="form-toggle-wrapper {variant} {size === 'sm' ? 'toggle-sm' : ''} {className}"
	class:is-disabled={disabled}
>
	<button
		type="button"
		class="toggle-control"
		role="switch"
		aria-checked={checked}
		aria-label={label}
		{disabled}
		onclick={handleChange}
		onkeydown={handleKeydown}
	>
		<input type="checkbox" {name} bind:checked class="toggle-input" tabindex="-1" {disabled} />

		<span class="toggle-track" class:checked>
			<span class="toggle-thumb"></span>
		</span>
	</button>

	<div
		class="toggle-content"
		onclick={handleChange}
		onkeydown={handleKeydown}
		role="button"
		tabindex="0"
	>
		<span class="toggle-label">{label}</span>
		{#if description}
			<span class="toggle-description">{description}</span>
		{/if}
	</div>
</div>

<style>
	.form-toggle-wrapper {
		display: flex;
		align-items: flex-start;
		gap: 12px;
		cursor: pointer;
	}

	.form-toggle-wrapper.is-disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Card variant */
	.form-toggle-wrapper.card {
		flex-direction: row-reverse;
		justify-content: space-between;
		padding: 16px;
		background: var(--white, #dbe8f4);
		border: 1px solid var(--gray-200, #e2e8f0);
		border-radius: var(--radius-button, 14px);
		transition: all 0.2s ease;
	}

	.form-toggle-wrapper.card:hover:not(.is-disabled) {
		border-color: var(--gray-300, #cbd5e1);
	}

	/* Toggle control */
	.toggle-control {
		position: relative;
		display: flex;
		align-items: center;
		padding: 0;
		background: none;
		border: none;
		cursor: inherit;
		flex-shrink: 0;
	}

	.toggle-input {
		position: absolute;
		opacity: 0;
		width: 0;
		height: 0;
	}

	/* Toggle track */
	.toggle-track {
		position: relative;
		display: inline-flex;
		align-items: center;
		width: 48px;
		height: 28px;
		background: var(--gray-200, #e2e8f0);
		border-radius: 100px;
		transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
	}

	.toggle-sm .toggle-track {
		width: 40px;
		height: 24px;
	}

	.toggle-track.checked {
		background: var(--blu-primary, #0066ff);
	}

	/* Toggle thumb */
	.toggle-thumb {
		position: absolute;
		left: 3px;
		width: 22px;
		height: 22px;
		background: var(--white, #dbe8f4);
		border-radius: 50%;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);
		transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
	}

	.toggle-sm .toggle-thumb {
		width: 18px;
		height: 18px;
	}

	.toggle-track.checked .toggle-thumb {
		transform: translateX(20px);
	}

	.toggle-sm .toggle-track.checked .toggle-thumb {
		transform: translateX(16px);
	}

	/* Hover states */
	.toggle-control:hover .toggle-track:not(.checked) {
		background: var(--gray-300, #cbd5e1);
	}

	.toggle-control:hover .toggle-track.checked {
		background: var(--blu-primary-hover, #0052cc);
	}

	/* Focus states */
	.toggle-control:focus-visible .toggle-track {
		box-shadow: 0 0 0 3px rgba(0, 102, 255, 0.2);
	}

	/* Content */
	.toggle-content {
		display: flex;
		flex-direction: column;
		gap: 2px;
		min-width: 0;
	}

	.toggle-label {
		font-size: 14px;
		font-weight: 500;
		color: var(--gray-900, #0f172a);
		line-height: 1.4;
	}

	.toggle-description {
		font-size: 13px;
		color: var(--gray-500, #64748b);
		line-height: 1.4;
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.toggle-track,
		.toggle-thumb,
		.form-toggle-wrapper.card {
			transition: none;
		}
	}
</style>

// apps/web/src/components/forms/FormToggle.tsx
import type { ComponentChildren } from 'preact';
import { cn } from '@/lib/utils';

type ToggleSize = 'sm' | 'md';
type ToggleVariant = 'default' | 'card';

interface FormToggleProps {
  label?: string;
  description?: string;
  name?: string;
  checked?: boolean;
  disabled?: boolean;
  size?: ToggleSize;
  variant?: ToggleVariant;
  className?: string;
  onChange?: (checked: boolean) => void;
}

const TRACK_SIZES = {
  sm: { width: 40, height: 24 },
  md: { width: 48, height: 28 },
} as const;

const THUMB_SIZES = {
  sm: { size: 18, offset: 3 },
  md: { size: 22, offset: 3 },
} as const;

export function FormToggle({
  label,
  description,
  name,
  checked = false,
  disabled = false,
  size = 'md',
  variant = 'default',
  className,
  onChange,
}: FormToggleProps) {
  const track = TRACK_SIZES[size];
  const thumb = THUMB_SIZES[size];
  const translateDistance = track.width - thumb.size - thumb.offset * 2;

  const handleClick = () => {
    if (disabled) return;
    onChange?.(!checked);
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    if (disabled) return;
    if (event.key === ' ' || event.key === 'Enter') {
      event.preventDefault();
      onChange?.(!checked);
    }
  };

  const isCard = variant === 'card';

  return (
    <div
      class={cn(
        'flex items-start gap-3 cursor-pointer',
        isCard && 'p-4 rounded-[var(--radius-sm)] border border-gray-200 bg-white transition-[border-color,background-color] duration-200 ease-in-out',
        isCard && checked && 'border-[var(--blu-primary)] bg-[rgba(0,102,255,0.04)]',
        disabled && 'opacity-50 cursor-not-allowed',
        className,
      )}
      role="switch"
      aria-checked={checked}
      aria-disabled={disabled}
      tabIndex={disabled ? -1 : 0}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      {(label || description) && (
        <div class="flex-1 flex flex-col gap-0.5 min-w-0">
          {label && <span class="text-[15px] font-medium text-gray-900 leading-[1.4]">{label}</span>}
          {description && <span class="text-[13px] text-gray-500 leading-normal">{description}</span>}
        </div>
      )}

      <div
        class={cn(
          'relative shrink-0 rounded-full bg-gray-200 transition-colors duration-200 ease-in-out cursor-pointer',
          checked && 'bg-[var(--blu-primary)]',
        )}
        style={{ width: track.width, height: track.height }}
      >
        <div
          class="absolute top-1/2 rounded-full bg-white shadow-[0_1px_3px_rgba(0,0,0,0.2)] transition-transform duration-200 ease-in-out"
          style={{
            width: thumb.size,
            height: thumb.size,
            left: thumb.offset,
            transform: checked
              ? `translateY(-50%) translateX(${translateDistance}px)`
              : 'translateY(-50%) translateX(0px)',
          }}
        />
      </div>

      {name && (
        <input
          type="checkbox"
          name={name}
          checked={checked}
          disabled={disabled}
          class="sr-only"
          tabIndex={-1}
          aria-hidden="true"
        />
      )}
    </div>
  );
}
