// apps/web/src/components/ui/FeedbackButton.tsx
import { useState, useCallback } from 'preact/hooks'
import { MessageCircle, X, Send, CheckCircle } from 'lucide-react'
import { useI18nStore } from '@/lib/i18n'
import { useAppStateStore } from '@/stores/appStateStore'
import { cn } from '@/lib/utils'

const CATEGORIES = [
  { value: 'bug', key: 'feedback.bug' },
  { value: 'feature', key: 'feedback.feature' },
  { value: 'general', key: 'feedback.general' },
  { value: 'praise', key: 'feedback.praise' },
] as const

export function FeedbackButton() {
  const { t } = useI18nStore()
  const { isRecordingMode, isModalOpen, setModalOpen } = useAppStateStore()

  const [open, setOpen] = useState(false)
  const [comment, setComment] = useState('')
  const [category, setCategory] = useState<string>('general')
  const [submitting, setSubmitting] = useState(false)
  const [success, setSuccess] = useState(false)

  const shouldHide = isRecordingMode || isModalOpen
  const canSubmit = comment.trim().length > 0 && !submitting

  const reset = useCallback(() => {
    setComment('')
    setCategory('general')
    setSubmitting(false)
    setSuccess(false)
  }, [])

  const close = useCallback(() => {
    setOpen(false)
    setModalOpen(false)
    reset()
  }, [reset, setModalOpen])

  const openModal = useCallback(() => {
    setOpen(true)
    setModalOpen(true)
  }, [setModalOpen])

  const submit = useCallback(async () => {
    if (!canSubmit) return
    setSubmitting(true)
    try {
      await fetch('/api/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          comment: comment.trim(),
          category,
          pageContext: window.location.pathname,
        }),
      })
      setSuccess(true)
      setTimeout(close, 1500)
    } catch {
      setSubmitting(false)
    }
  }, [canSubmit, comment, category, close])

  return (
    <>
      {/* FAB */}
      {!shouldHide && !open && (
        <button
          class="fixed bottom-[calc(80px+env(safe-area-inset-bottom,0px))] right-4 z-[1000] w-12 h-12 rounded-full border-none bg-[#0066ff] text-white flex items-center justify-center cursor-pointer shadow-[0_4px_16px_rgba(0,102,255,0.4)]"
          onClick={openModal}
          aria-label="Send feedback"
        >
          <MessageCircle size={22} />
        </button>
      )}

      {/* Modal */}
      {open && (
        <div
          class="fixed inset-0 z-[1001] bg-black/40 backdrop-blur-sm flex items-center justify-center p-4"
          onClick={close}
          onKeyDown={(e) => { if (e.key === 'Escape') close() }}
        >
          <div
            class="bg-white/85 backdrop-blur-[20px] border border-white/50 rounded-2xl p-6 w-full max-w-[420px] shadow-[0_8px_32px_rgba(0,102,255,0.15)]"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-modal="true"
          >
            {success ? (
              <div class="flex flex-col items-center gap-3 py-8 text-center">
                <CheckCircle size={48} color="#0066FF" />
                <p class="m-0 text-[1.05rem] font-medium text-[#1a1a2e]">{t('feedback.thanks')}</p>
              </div>
            ) : (
              <>
                <div class="flex justify-between items-center mb-4">
                  <h2 class="m-0 text-[1.15rem] font-semibold text-[#1a1a2e]">{t('feedback.title')}</h2>
                  <button
                    class="bg-transparent border-none cursor-pointer text-[#666] p-1 rounded-lg"
                    onClick={close}
                    aria-label="Close"
                  >
                    <X size={20} />
                  </button>
                </div>

                <div class="flex flex-wrap gap-2 mb-4">
                  {CATEGORIES.map((cat) => (
                    <button
                      key={cat.value}
                      class={cn(
                        'px-3.5 py-1.5 rounded-[20px] text-[0.85rem] cursor-pointer border',
                        category === cat.value
                          ? 'border-[#0066ff] bg-[rgba(0,102,255,0.1)] text-[#0066ff] font-medium'
                          : 'border-[#ddd] bg-white/60 text-[#444] font-normal',
                      )}
                      onClick={() => setCategory(cat.value)}
                    >
                      {t(cat.key)}
                    </button>
                  ))}
                </div>

                <div class="relative mb-4">
                  <textarea
                    value={comment}
                    onInput={(e) => setComment((e.target as HTMLTextAreaElement).value)}
                    maxLength={2000}
                    rows={5}
                    placeholder={t('feedback.placeholder')}
                    class="w-full border border-[#ddd] rounded-xl p-3 text-[0.9rem] resize-y bg-white/60 font-[inherit] box-border"
                  />
                  <span class="absolute bottom-2 right-3 text-xs text-[#999]">
                    {comment.length}/2000
                  </span>
                </div>

                <button
                  class={cn(
                    'w-full p-3 border-none rounded-xl bg-[#0066ff] text-white text-[0.95rem] font-medium flex items-center justify-center gap-2',
                    canSubmit ? 'opacity-100 cursor-pointer' : 'opacity-50 cursor-not-allowed',
                  )}
                  disabled={!canSubmit}
                  onClick={submit}
                >
                  {submitting ? t('feedback.sending') : (
                    <>
                      <Send size={16} />
                      {t('feedback.submit')}
                    </>
                  )}
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </>
  )
}

// src/lib/components/FeedbackButton.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { t } from '$lib/i18n';
	import MessageCircle from 'lucide-svelte/icons/message-circle';
	import X from 'lucide-svelte/icons/x';
	import Send from 'lucide-svelte/icons/send';
	import CheckCircle from 'lucide-svelte/icons/check-circle';

	let open = $state(false);
	let comment = $state('');
	let category = $state<'bug' | 'feature' | 'general' | 'praise'>('general');
	let submitting = $state(false);
	let success = $state(false);

	let charCount = $derived(comment.length);
	let canSubmit = $derived(comment.trim().length > 0 && !submitting);

	const categories = [
		{ value: 'bug', key: 'feedback.bug' },
		{ value: 'feature', key: 'feedback.feature' },
		{ value: 'general', key: 'feedback.general' },
		{ value: 'praise', key: 'feedback.praise' }
	] as const;

	function reset() {
		comment = '';
		category = 'general';
		submitting = false;
		success = false;
	}

	function close() {
		open = false;
		reset();
	}

	async function submit() {
		if (!canSubmit) return;
		submitting = true;
		try {
			await fetch('/api/feedback', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					comment: comment.trim(),
					category,
					pageContext: $page.url.pathname
				})
			});
			success = true;
			setTimeout(() => {
				close();
			}, 1500);
		} catch {
			submitting = false;
		}
	}
</script>

<!-- Floating button -->
<button class="fab" onclick={() => (open = true)} aria-label="Send feedback">
	<MessageCircle size={22} />
</button>

<!-- Modal -->
{#if open}
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div class="overlay" onkeydown={(e) => e.key === 'Escape' && close()} onclick={close}>
		<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
		<div
			class="modal"
			onclick={(e) => e.stopPropagation()}
			onkeydown={(e) => e.stopPropagation()}
			role="dialog"
			aria-modal="true"
			tabindex="-1"
		>
			{#if success}
				<div class="success">
					<CheckCircle size={48} color="#0066FF" />
					<p>{$t('feedback.thanks')}</p>
				</div>
			{:else}
				<div class="header">
					<h2>{$t('feedback.title')}</h2>
					<button class="close-btn" onclick={close} aria-label="Close">
						<X size={20} />
					</button>
				</div>

				<fieldset class="categories">
					{#each categories as cat (cat.value)}
						<label class:selected={category === cat.value}>
							<input type="radio" name="category" value={cat.value} bind:group={category} />
							{$t(cat.key)}
						</label>
					{/each}
				</fieldset>

				<div class="textarea-wrap">
					<textarea
						bind:value={comment}
						maxlength={2000}
						rows={5}
						placeholder={$t('feedback.placeholder')}
					></textarea>
					<span class="char-count">{charCount}/2000</span>
				</div>

				<button class="submit-btn" disabled={!canSubmit} onclick={submit}>
					{#if submitting}
						{$t('feedback.sending')}
					{:else}
						<Send size={16} />
						{$t('feedback.submit')}
					{/if}
				</button>
			{/if}
		</div>
	</div>
{/if}

<style>
	.fab {
		position: fixed;
		bottom: 80px;
		right: 16px;
		z-index: 1000;
		width: 48px;
		height: 48px;
		border-radius: 50%;
		border: none;
		background: #0066ff;
		color: white;
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		box-shadow: 0 4px 16px rgba(0, 102, 255, 0.4);
		transition:
			transform 0.2s,
			box-shadow 0.2s;
	}
	.fab:hover {
		transform: scale(1.08);
		box-shadow: 0 6px 20px rgba(0, 102, 255, 0.5);
	}

	.overlay {
		position: fixed;
		inset: 0;
		z-index: 1001;
		background: rgba(0, 0, 0, 0.4);
		backdrop-filter: blur(4px);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 16px;
	}

	.modal {
		background: rgba(255, 255, 255, 0.85);
		backdrop-filter: blur(20px);
		border: 1px solid rgba(255, 255, 255, 0.5);
		border-radius: 16px;
		padding: 24px;
		width: 100%;
		max-width: 420px;
		box-shadow: 0 8px 32px rgba(0, 102, 255, 0.15);
	}

	.header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 16px;
	}
	.header h2 {
		margin: 0;
		font-size: 1.15rem;
		font-weight: 600;
		color: #1a1a2e;
	}
	.close-btn {
		background: none;
		border: none;
		cursor: pointer;
		color: #666;
		padding: 4px;
		border-radius: 8px;
	}
	.close-btn:hover {
		background: rgba(0, 0, 0, 0.06);
	}

	.categories {
		display: flex;
		flex-wrap: wrap;
		gap: 8px;
		border: none;
		padding: 0;
		margin: 0 0 16px;
	}
	.categories label {
		padding: 6px 14px;
		border-radius: 20px;
		font-size: 0.85rem;
		cursor: pointer;
		border: 1px solid #ddd;
		background: rgba(255, 255, 255, 0.6);
		transition: all 0.15s;
		color: #444;
	}
	.categories label.selected {
		border-color: #0066ff;
		background: rgba(0, 102, 255, 0.1);
		color: #0066ff;
		font-weight: 500;
	}
	.categories input {
		display: none;
	}

	.textarea-wrap {
		position: relative;
		margin-bottom: 16px;
	}
	textarea {
		width: 100%;
		border: 1px solid #ddd;
		border-radius: 12px;
		padding: 12px;
		font-size: 0.9rem;
		resize: vertical;
		background: rgba(255, 255, 255, 0.6);
		font-family: inherit;
		box-sizing: border-box;
	}
	textarea:focus {
		outline: none;
		border-color: #0066ff;
		box-shadow: 0 0 0 3px rgba(0, 102, 255, 0.1);
	}
	.char-count {
		position: absolute;
		bottom: 8px;
		right: 12px;
		font-size: 0.75rem;
		color: #999;
	}

	.submit-btn {
		width: 100%;
		padding: 12px;
		border: none;
		border-radius: 12px;
		background: #0066ff;
		color: white;
		font-size: 0.95rem;
		font-weight: 500;
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 8px;
		transition: opacity 0.15s;
	}
	.submit-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
	.submit-btn:not(:disabled):hover {
		background: #0055dd;
	}

	.success {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 12px;
		padding: 32px 0;
		text-align: center;
	}
	.success p {
		margin: 0;
		font-size: 1.05rem;
		font-weight: 500;
		color: #1a1a2e;
	}
</style>
