// src/lib/components/BottomNav.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { fly } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import Mic from 'lucide-svelte/icons/mic';
	import FileText from 'lucide-svelte/icons/file-text';
	import Settings from 'lucide-svelte/icons/settings';
	import { t } from '$lib/i18n';
	import { pageTransition } from '$lib/stores/pageTransition';
	import { isRecordingMode, isModalOpen } from '$lib/stores/appState';

	const isActive = (href: string) => {
		const pathname = $page.url.pathname;
		if (href === '/dashboard') {
			return pathname === '/dashboard';
		}
		return pathname.startsWith(href);
	};

	function handleNavClick(e: MouseEvent, href: string) {
		e.preventDefault();
		// Don't navigate if already on the page
		if (isActive(href)) return;
		pageTransition.navigate(href);
	}

	// Get active index for indicator position
	const activeIndex = $derived.by(() => {
		const pathname = $page.url.pathname;
		if (pathname === '/dashboard') return 1; // Record (center)
		if (pathname.startsWith('/dashboard/documents')) return 0; // Documents (left)
		if (pathname.startsWith('/dashboard/settings')) return 2; // Settings (right)
		return 1; // Default to center
	});
</script>

{#if !$isRecordingMode && !$isModalOpen}
<nav class="bottom-nav" transition:fly={{ y: 100, duration: 300, easing: cubicOut }}>
	<!-- Animated indicator -->
	<div class="indicator" style="transform: translateX({activeIndex * 58}px)"></div>

	<a
		href="/dashboard/documents"
		class="nav-item"
		class:active={isActive('/dashboard/documents')}
		onclick={(e) => handleNavClick(e, '/dashboard/documents')}
		aria-label={$t('nav.documents')}
		data-tutorial="nav-documents"
	>
		<FileText size={28} strokeWidth={isActive('/dashboard/documents') ? 2 : 1.5} />
	</a>

	<a
		href="/dashboard"
		class="nav-item"
		class:active={isActive('/dashboard')}
		onclick={(e) => handleNavClick(e, '/dashboard')}
		aria-label={$t('nav.record')}
	>
		<Mic size={28} strokeWidth={isActive('/dashboard') ? 2 : 1.5} />
	</a>

	<a
		href="/dashboard/settings"
		class="nav-item"
		class:active={isActive('/dashboard/settings')}
		onclick={(e) => handleNavClick(e, '/dashboard/settings')}
		aria-label={$t('nav.settings')}
		data-tutorial="nav-settings"
	>
		<Settings size={28} strokeWidth={isActive('/dashboard/settings') ? 2 : 1.5} />
	</a>
</nav>
{/if}

<style>
	.bottom-nav {
		position: fixed;
		bottom: var(--space-5);
		left: 50%;
		transform: translateX(-50%);
		display: flex;
		justify-content: center;
		align-items: center;
		gap: 6px;
		background: rgba(203, 218, 233, 0.65);
		backdrop-filter: blur(20px) saturate(150%);
		-webkit-backdrop-filter: blur(20px) saturate(150%);
		padding: 6px;
		padding-bottom: calc(6px + var(--safe-area-bottom));
		border-radius: var(--radius-full);
		box-shadow: 0 4px 24px rgba(0, 40, 100, 0.1);
		z-index: var(--z-fixed);
		transition: transform var(--duration-normal) var(--ease-out-expo);
	}

	.indicator {
		position: absolute;
		left: 6px;
		width: 52px;
		height: 52px;
		background: rgba(255, 255, 255, 0.6);
		border-radius: var(--radius-full);
		transition: transform var(--duration-normal) var(--ease-out-expo);
		box-shadow: 0 2px 8px rgba(0, 40, 100, 0.08);
	}

	.nav-item {
		position: relative;
		display: flex;
		align-items: center;
		justify-content: center;
		width: 52px;
		height: 52px;
		color: var(--gray-500);
		text-decoration: none;
		transition: color var(--duration-fast) ease;
		border-radius: var(--radius-full);
		z-index: 1;
	}

	.nav-item:hover {
		color: var(--gray-700);
	}

	.nav-item.active {
		color: var(--blu-primary);
	}

	.nav-item:focus-visible {
		outline: 2px solid var(--blu-primary);
		outline-offset: 2px;
	}
</style>

// apps/web/src/components/layout/BottomNav.tsx
import { useRef } from 'preact/hooks'
import { useLocation, Link } from 'wouter'
import { FileText, Mic, Settings } from 'lucide-react'
import { useAppStateStore } from '@/stores/appStateStore'

const NAV_ITEMS = [
  { href: '/dashboard/documents', Icon: FileText, tutorial: 'nav-documents' },
  { href: '/dashboard', Icon: Mic, tutorial: undefined },
  { href: '/dashboard/settings', Icon: Settings, tutorial: 'nav-settings' },
] as const

function getActiveIndex(pathname: string): number {
  if (pathname.startsWith('/dashboard/documents')) return 0
  if (pathname.startsWith('/dashboard/settings')) return 2
  return 1
}

export function BottomNav() {
  const { isRecordingMode, modalCount, isSelectMode } = useAppStateStore()
  const [location] = useLocation()
  const navRef = useRef<HTMLElement>(null)
  const activeIndex = getActiveIndex(location)

  if (isRecordingMode || modalCount > 0 || isSelectMode || location.startsWith('/dashboard/review')) return null

  const pct = ((2 * activeIndex + 1) / 6) * 100

  return (
    <>
      <style>{navStyles}</style>
      <nav ref={navRef} class="bn-pill">
        <div class="bn-indicator-track">
          <div class="bn-indicator" style={{ left: `${pct}%` }} />
        </div>

        {NAV_ITEMS.map(({ href, Icon, tutorial }, i) => {
          const isActive = i === activeIndex
          return (
            <Link
              key={href}
              href={href}
              data-tutorial={tutorial}
              aria-current={isActive ? 'page' : undefined}
              class={`bn-item ${isActive ? 'bn-active' : ''}`}
            >
              <Icon size={24} strokeWidth={isActive ? 2 : 1.5} />
            </Link>
          )
        })}
      </nav>
    </>
  )
}

const navStyles = `
  .bn-pill {
    position: fixed;
    bottom: 12px;
    left: 50%;
    transform: translateX(-50%);
    width: calc(100% - 32px);
    max-width: 240px;
    display: flex;
    align-items: center;
    background: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border-radius: 9999px;
    padding: 6px;
    box-shadow: 0 4px 24px rgba(0, 40, 100, 0.12), 0 1px 4px rgba(0, 0, 0, 0.06);
    z-index: var(--z-fixed, 300);
    margin-bottom: env(safe-area-inset-bottom, 0px);
  }

  .bn-indicator-track {
    position: absolute;
    inset: 6px;
    pointer-events: none;
  }

  .bn-indicator {
    position: absolute;
    width: 48px;
    height: 48px;
    border-radius: 50%;
    background: rgba(0, 102, 255, 0.12);
    top: 0;
    transform: translateX(-50%);
    transition: left 250ms cubic-bezier(0.16, 1, 0.3, 1);
  }

  .bn-item {
    display: flex;
    align-items: center;
    justify-content: center;
    flex: 1 1 0%;
    height: 48px;
    text-decoration: none;
    color: var(--gray-400, #94a3b8);
    position: relative;
    z-index: 1;
    transition: color 200ms ease;
  }

  .bn-item.bn-active {
    color: var(--blu-primary, #0066ff);
  }
`
